---
# tasks file for zookeeper
- name: Installing zookeeper
  yum:
    name: confluent-kafka-2.11.noarch
    state: present

- name: ensure group "zookeeper" exists
  group:
    name: zookeeper
    state: present

- name: ensure user "zookeeper" exists
  user:
    name: zookeeper
    group: zookeeper
    shell: /bin/bash

- name: ensure zookeeper directories exists
  file:
    path: "{{ item }}"
    owner: zookeeper
    group: zookeeper
    state: directory
    mode: 0755
  with_items:
    - [ "/var/log/zookeeper", "/var/lib/zookeeper", "/var/log/kafka" ]

- name: ensure file exists
  copy: content={{ ansible_hostname[-3:] }} dest=/var/lib/zookeeper/myid
        force=yes group=zookeeper owner=zookeeper mode=0644

- name: install zookeeper service definition
  copy: src=zookeeper.service dest=/etc/systemd/system/zookeeper.service owner=root group=root mode=0644
  notify:
    - zookeeper-restart

- name: zookeeper-enable
  service: name=zookeeper.service enabled=yes

- name: install zookeeper service configuraiton
  copy: src=zookeeper.conf dest=/etc/sysconfig/zookeeper.conf owner=root group=root mode=0644
  notify:
      - zookeeper-restart

- name: configure zookeeper cluster
  template: src=zookeeper.properties.j2 dest=/etc/kafka/zookeeper.properties mode=0644
  notify:
      - zookeeper-restart

- name: start zookeeper service
  service: name=zookeeper.service state=started