---
  - hosts: all
    become: true
    tasks:

    - name: add the Confluent Platform repos (Dist)
      yum_repository:
        name: Confluent.dist
        file: confluent
        description: Confluent Yum Repos (Dist)
        baseurl: https://packages.confluent.io/rpm/4.0/7
        gpgcheck: 1
        gpgkey: https://packages.confluent.io/rpm/4.0/archive.key
        enabled: yes

    - name: add the Confluent Platform repos
      yum_repository:
        name: Confluent
        file: confluent
        description: Confluent Yum Repos
        baseurl: https://packages.confluent.io/rpm/4.0/
        gpgcheck: 1
        gpgkey: https://packages.confluent.io/rpm/4.0/archive.key
        enabled: yes

    - name: install OpenJDK
      yum:
        name: java-1.8.0-openjdk.x86_64
        state: present